name = "glency"
version = "1.0.1"
description = "Tiny Gleam dependency injection. Make IO functions unit tests friendly."
licences = ["MIT"]
repository = { type = "github", user = "darky", repo = "glency" }
gleam = ">= 1.2.1"

[dependencies]
carpenter = ">= 0.3.1"
gleaf = ">= 1.0.0"
gleam_stdlib = ">= 0.34.0 and < 2.0.0"
gluple = ">= 2.2.0"

[dev-dependencies]
cleam = ">= 1.5.1"
gleeunit = ">= 1.0.0 and < 2.0.0"
